    
    create table cliente_fisico (
       cpf varchar(11) not null unique,
        id int8 not null,
        primary key (id)
    );
    
    create table cliente_juridico (
       cnpj varchar(14) not null unique,
        id int8 not null,
        primary key (id)
    );
    
    create table conta (
       id int8 generated by default as identity,
        movimentacao_credito int4,
        movimentacao_debito int4,
        saldo_atual numeric(19, 2),
        saldo_inicial numeric(19, 2),
        total_movimentacao int4,
        valor_pago_movimentacao numeric(19, 2),
        pessoa_id int8 not null,
        primary key (id)
    );
    
    create table pessoa (
       id int8 generated by default as identity,
        data_cadastro date not null,
        bairro varchar(255),
        cep varchar(8),
        cidade varchar(255),
        complemento varchar(255),
        numero varchar(255),
        rua varchar(255),
        uf varchar(255),
        is_pessoa_fisica boolean,
        nome varchar(255) not null,
        telefone varchar(11) not null,
        primary key (id)
    );
    
    alter table if exists cliente_fisico 
       add constraint fk_cliente_fisico_id 
       foreign key (id) 
       references pessoa;
    
    alter table if exists cliente_juridico 
       add constraint fk_cliente_juridico_id 
       foreign key (id) 
       references pessoa;
    
    alter table if exists conta 
       add constraint fk_conta_pessoa_id 
       foreign key (pessoa_id) 
       references pessoa;